### ISSUE TITLE
Consolidate repo

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask-gateway-helm-repo#1]
It would be good to have a single helm repo for Dask related charts.

I've proposed in dask/helm-chart#17 that we create a repo over there using `gh-pages` in the same way that has been done here and put it at https://helm.dask.org.

I hadn't realised this repo existed. Could we look at combining the two as it would add scope for adding more charts in future all under a single Dask org repo too?

**Comment by jacobtomlinson** [comment]
To clarify after re-reading as I'm not sure I worded it well. I'm proposing consolidating the publishing location, not the actual source of the charts.

**Comment by consideRatio** [comment]
Let's close this and focus discussion in https://github.com/dask/dask-gateway/issues/436.
