### ISSUE TITLE
Missing Chart for 0.9.0 release

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask-gateway-helm-repo#2]
@jcrist https://github.com/dask/dask-gateway-helm-repo/commit/172357676ee958ef8f837945dd2377c30c60073e updated the index, but the actual `https://dask.org/dask-gateway-helm-repo/dask-gateway-0.9.0.tgz` (maybe a gitignore issue?).

**Comment by jcrist** [comment]
Thanks, should be fixed now. Missed adding it to the commit.
